-- 车辆表
CREATE TABLE IF NOT EXISTS `uc_cars` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '车辆ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '发布用户ID',
  `title` varchar(200) NOT NULL DEFAULT '' COMMENT '车辆标题',
  `brand` varchar(50) NOT NULL DEFAULT '' COMMENT '品牌',
  `series` varchar(50) NOT NULL DEFAULT '' COMMENT '车系',
  `model` varchar(50) NOT NULL DEFAULT '' COMMENT '车型',
  `year` int(4) NOT NULL DEFAULT '0' COMMENT '年份',
  `mileage` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '里程数(万公里)',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '价格(万元)',
  `original_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价(万元)',
  `color` varchar(20) NOT NULL DEFAULT '' COMMENT '颜色',
  `fuel_type` varchar(20) NOT NULL DEFAULT '' COMMENT '燃料类型',
  `transmission` varchar(20) NOT NULL DEFAULT '' COMMENT '变速箱',
  `displacement` varchar(20) NOT NULL DEFAULT '' COMMENT '排量',
  `emission_standard` varchar(20) NOT NULL DEFAULT '' COMMENT '排放标准',
  `description` text COMMENT '车辆描述',
  `images` text COMMENT '车辆图片(JSON)',
  `province` varchar(50) NOT NULL DEFAULT '' COMMENT '省份',
  `city` varchar(50) NOT NULL DEFAULT '' COMMENT '城市',
  `district` varchar(50) NOT NULL DEFAULT '' COMMENT '区县',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '详细地址',
  `contact_name` varchar(50) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `view_count` int(11) NOT NULL DEFAULT '0' COMMENT '浏览次数',
  `collect_count` int(11) NOT NULL DEFAULT '0' COMMENT '收藏次数',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0待审核 1已发布 2已下架 3已售出',
  `is_recommend` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否推荐 0否 1是',
  `is_hot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否热门 0否 1是',
  `create_time` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `brand` (`brand`),
  KEY `price` (`price`),
  KEY `status` (`status`),
  KEY `is_recommend` (`is_recommend`),
  KEY `is_hot` (`is_hot`),
  KEY `create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='车辆表';

